### PR TITLE
Quick fix to Ethernet shields not starting.

### PR DESCRIPTION
**Pull request by kingofkya**
Check to see if ip was set on Ethernet shield, if not it reboots.

 I also added a reset to the nrf if it fails but it seams that radio.Initialize dosen't return anything but true when its in TX mode, I cant see a bug in the lib might want to figure that out later, its safe to merge anyways with that bug.

This fixes my iffy Ethernet shields see if it works for you guys.

### CODE REVIEW

**Comment by gothambeat** [comment]
What is the best way to download/update the latest code for these sketches.  

 

 

Thanks.


 


Michael

 


Phone:  (609) 208-1852

Email: caputom@optonline.net 


Cell: (732) 371-1471

LinkedIn:  http://www.linkedin.com/in/michaelpcaputo


Fax:  (609) 208-9081

**Comment by kingofkya** [comment]
YOU might want to edit that post, you posted you number and other info on the internet for the spambot to copy...

https://github.com/komby/RFShowControl/pull/26


Also this is untested code that is not released yet, if you want to test it though you just need to grab the Ethernet sketch from my git repo.

**Comment by gothambeat** [comment]
Thanks.  Didn't realize it was replying to post.  I did it from my email.

**Comment by komby** [comment]
Merging in the changes from #26

**Pull request merged**
